### ISSUE TITLE
About GoogleAnalytics

### ISSUE THREAD

**Issue by yuangezhizao** [KawashiroNitori/Anubis#1]
In China , because of `GFW` , it may make your website loading too slow.
I suggest you replace it to `CNZZ` or `baidu_tongji`.

**Comment by KawashiroNitori** [comment]
Don't worry, Google Analytics is not blocked by GFW.

**Comment by KawashiroNitori** [comment]
You can't access any website on the Internet without login the authorization system of school.
BTW, the loader of GA is asynchronous, it may not affect the loading of website.
But I will remove the GA loader during school contest.

Thank you for contributing. :)

**Comment by yuangezhizao** [comment]
👌
